Ira/first
chummy-ch/Water-overflow pull request #11
Opened 2021-04-29 11:40 UTC by irockk

2021-04-29 11:48 UTC, chummy-ch requested changes
Should make some changes

2021-04-29 11:48 UTC, chummy-ch commented on lib/screens/MainScreen.dart
> +                          '3',
Its code duplication. If you use same widgets with the same params you can extract them to separete class and reuse them.

2021-04-29 11:48 UTC, chummy-ch commented on lib/screens/MainScreen.dart
> +                      SizedBox(width: SizeConfig.blockSizeVertical * 1.6),
It is better to create a const value instead of using a magic integer

2021-05-04 17:13 UTC, RuslanProgrammer commented
Oh, no. You maybe forgot to merge develop branch into your firstly!?

2021-05-05 09:05 UTC, chummy-ch approved these changes

2021-05-05 09:08 UTC, merged